/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class FormCardConstants {
  /**
   * Adapt the 5.0.
   */
  public static readonly FULL_PERCENT: Length = '100%';
  public static readonly CARD_CONTENT_WIDTH = '80%';
  public static readonly ACTION_TYPE: string = 'router';
  public static readonly ABILITY_NAME: string = 'EntryAbility';
  public static readonly OPACITY_LG: number = 0.8;
}