/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ArticleListItem } from './FormCardInfo';

export const ALL_ARTICLE_LISTS: ArticleListItem[] = [
  {
    id: 1,
    title: 'A small window to a bigger world with Live View',
    desc: 'Display real-time information everywhere.',
    detailsUrl: 'articlecols/articles/live-window-service/index.html',
    name: 'Development practice',
    isArticle: true,
  },
  {
    id: 2,
    title: 'Pick safely with Picker and let users stay in control',
    desc: 'A clean and secure new experience.',
    detailsUrl: 'articlecols/articles/native-safety/index.html',
    name: 'Development practice',
    isArticle: true,
  },
  {
    id: 3,
    title: 'Seamless transitions for a smooth visual journey',
    desc: 'Enjoy an exceptionally smooth experience.',
    detailsUrl: 'articlecols/articles/shared-element-transition/index.html',
    name: 'Development practice',
    isArticle: true,
  },
  {
    id: 4,
    title: 'Connect devices for a seamless experience',
    desc: 'Connect devices and transfer seamlessly.',
    detailsUrl: 'articlecols/articles/app-continuation/index.html',
    name: 'Development practice',
    isArticle: true,
  },
  {
    id: 5,
    title: 'AI image recognition for intelligent image processing',
    desc: 'Start a new era of intelligent image processing.',
    detailsUrl: 'articlecols/articles/smart-visual-recognition/index.html',
    name: 'Development practice',
    isArticle: true,
  },
  {
    id: 18,
    title: 'Multi-device UX design',
    desc: 'Provide characteristic scenario interfaces that fit app business scenarios for optimal adaptation and innovative design.',
    detailsUrl: 'articlecols/articles/native-ux-design/index.html',
    name: 'App experience design',
    isArticle: true,
  },
  {
    id: 22,
    title: 'App UX experience standards',
    desc: 'Learn HarmonyOS app UX standards in advance and quickly meet release requirements.',
    detailsUrl: 'articlecols/articles/ux-guidelines/index.html',
    name: 'App experience design',
    isArticle: true,
  },
  {
    id: 7,
    title: 'UX motion design',
    desc: 'HarmonyOS UX motion design improves the user experience across different scenarios and meets diverse needs.',
    detailsUrl: 'articlecols/articles/design-animation/index.html',
    name: 'App experience design',
    isArticle: true,
  },
  {
    id: 8,
    title: 'Layered architecture design',
    desc: 'HarmonyOS apps use a layered architecture and one codebase to support phones, PCs, 2-in-1 devices, and the complete 1+8 device ecosystem.',
    detailsUrl: 'articlecols/articles/layered-architecture-design/index.html',
    name: 'Feature development',
    isArticle: true,
  },
  {
    id: 12,
    title: 'HMOS Code Workshop adaptive development practice',
    desc: 'Apply the one-development, multi-device deployment approach to enable seamless collaboration and a consistent, efficient user experience.',
    detailsUrl: 'articlecols/articles/multi-adaptation/index.html',
    name: 'Feature development',
    isArticle: true,
  }
];
