/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ArticleListItem } from './FormCardInfo';

export const allArticleLists: ArticleListItem[] = [
  {
    id: 1,
    title: '小窗口大世界，智享实况窗服务',
    detailsUrl: 'articlecols/articles/live-window-service/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 2,
    title: 'Picker安心取，用户主导安全新体验',
    detailsUrl: 'articlecols/articles/native-safety/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 3,
    title: '一镜到底，畅享无界丝滑视觉之旅',
    detailsUrl: 'articlecols/articles/shared-element-transition/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 4,
    title: '跨设备互联，打造无缝流转极致体验',
    detailsUrl: 'articlecols/articles/app-continuation/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 5,
    title: 'AI识图，开启智能图像处理新纪元',
    detailsUrl: 'articlecols/articles/smart-visual-recognition/index.html',
    name: '开发实践',
    isArticle: true,
  },
  {
    id: 18,
    title: '多端UX设计',
    detailsUrl: 'articlecols/articles/native-ux-design/index.html',
    name: '应用体验设计',
    isArticle: true,
  },
  {
    id: 22,
    title: '应用UX体验标准',
    detailsUrl: 'articlecols/articles/ux-guidelines/index.html',
    name: '应用体验设计',
    isArticle: true,
  },
  {
    id: 7,
    title: 'UX动效设计',
    detailsUrl: 'articlecols/articles/design-animation/index.html',
    name: '应用体验设计',
    isArticle: true,
  },
  {
    id: 8,
    title: '分层架构设计',
    detailsUrl: 'articlecols/articles/layered-architecture-design/index.html',
    name: '功能开发',
    isArticle: true,
  },
  {
    id: 12,
    title: 'HMOS代码工坊一多开发实践',
    detailsUrl: 'articlecols/articles/multi-adaptation/index.html',
    name: '功能开发',
    isArticle: true,
  }
];